### ISSUE TITLE
Pardus installer translation

### ISSUE THREAD

**Issue by hugok79** [pardus/pardus-installer#1]
Hi, this is more a question than an issue...
Is **pardus-intaller** synchronized from Linux Mint **live-installer** https://translations.launchpad.net/linuxmint/latest/+pots/live-installer/pt/+translate (portuguese) or can I translate it manual and make a PR here to update the Portuguese translation?

https://translations.launchpad.net/linuxmint/latest/+lang/pt
By the way, I'am also the Linux Mint Portuguese translator

Regards,
Hugo Carvalho

**Comment by sulincix** [comment]
Linux mint live installer and pardus installer are different project. pardus installer fork of early version of lmde installer.

**Comment by hugok79** [comment]
Thank you for answering. I'll continue translating and making pull requests.
